micronaut:
  application:
    name: myapplication
    instance: ${random.uuid}
    version: 0.1
  server:
    port: 8080
    cors:
      enabled: true
  router:
    static-resources:
         swagger:
          enabled: true
          mapping: /swagger/**
          paths: 
          - classpath:META-INF/swagger
          - classpath:view/swagger
          
    versioning:
          enabled: true
          default-version: 3
          parameter:
              enabled: true 
              names: 'v,api-version' 
          header:
              enabled: true 
              names: 
                  - 'X-API-VERSION'
                  - 'Accept-Version'   
              
  metrics:
     enabled: true
     export:
         prometheus:
         enabled: true
graphql:
  enabled: true
  graphiql:
    enabled: true
    path: /graphiql
    template-path: classpath:graphiql/index.html
    page-title: GraphiQL
    
 
scheduler:
  enabled: true
  cron: '0 30 4 1/1 * ?'